sudo: required

services:
  - docker

before_install:
  - docker build -t manishn9887/celeryapp .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u" "$DOCKER_ID" --password-stdin
  - docker push manishn9887/celeryapp