language: python
python:
  - 3.9.1

sudo: required

services:
  - docker

before_install:
  - docker build -t manishn9887/celeryapp .

before_script:
  - pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u" "$DOCKER_ID" --password-stdin
  - docker push manishn9887/celeryapp