
language: python

python:
  - 3.9.1

sudo: required

services:
  - docker
  - redis

before_install:
  - docker build -t manishn9887/celeryapp .

before_script:
  - pip install docker-compose

script:
  - python manage.py test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push manishn9887/celeryapp


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: celeryapp
  env: Celeryapp-env
  bucket_name: elasticbeanstalk-us-east-2-758120010381
  bucket_path: celeryapp
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
