version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery worker -A core -l info -c 4
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

#  worker:
#    build: .
#    image: &img worker
#    command: [ celery, worker, --app=worker.app, --pool=gevent, --concurrency=20, --loglevel=INFO ]
#    environment: &env
#      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
#    depends_on:
#      - celery-beat
#      - redis
#    restart: 'no'
#    volumes:
#      - .:/code


volumes:
  postgres_data: